#––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
# `compose.yaml`
# @organization: Semantyk
# @project: Ecosystem
#
# @file: This file defines the Docker Compose services for the knowledge app.
#
# @created: 2026-09-02 11:06
# @modified: 2026-09-02 13:23
#
# @since: 0.1.0-alpha.42
# @version: 0.1.0-alpha.45
#
# @author: Semantyk Team
# @maintainer: Daniel Bakas <daniel@semantyk.com>
# @copyright: Semantyk © 2026
#––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

name: semantyk

networks:
  knowledge:
    name: knowledge
    driver: bridge
  semantyk:
    name: semantyk
    driver: bridge

services:
  knowledge:
    container_name: knowledge
    build: .
    env_file:
      - .env
    ports:
      - "3031:3030"
    volumes:
      - ./src/data:/fuseki/databases
      - ./src/config:/fuseki/configuration
      - ./src/logs:/fuseki/logs
    networks:
      - knowledge
      - semantyk
