' ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
' # `flow.puml`
' @organization: Semantyk
' @project: Ecosystem
'
' @file: This file defines the `flow.puml` diagram.
'
' @created: 2026-08-29 11:27
' @modified: 2026-08-29 20:04
'
' @since: 0.1.0-alpha.0
' @version: 0.1.0-alpha.0
'
' @author: Semantyk Team
' @maintainer: Daniel Bakas <daniel@semantyk.com>
'
' @copyright: Semantyk © 2026
' ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

@startuml "FLUJO DE LA ESTRATEGIA"

'* Imports
!include ../../../../src/packages/ux/styles/main.styles.puml

'* Main
mainframe <<flujo>>\n**GOBERNANZA ESTRATÉGICA**

start

partition "CAPAS DE ARQUITECTURA" {
    split
        :VALOR;
    split again
        :PROCESOS;
    split again
        :APLICACIONES;
    split again
        :INFORMACIÓN;
    split again
        :TECNOLOGÍA;
    end split
}

split
    partition "LEAN CANVAS" {
        split
            split
                :PROBLEMA;
            split again
                :PÚBLICO OBJETIVO;
            end split
            :PROPUESTA DE VALOR;
            :SOLUCIÓN;
            :VENTAJA ESPECIAL;
            :CANALES;
            split
                :ESTRUCTURA DE COSTOS;
            split again
                :FLUJOS DE INGRESO;
            end split
            :MÉTRICAS CLAVE;
        end split
    }

split again
    partition "BUSINESS MODEL CANVAS" {
        split
            :PÚBLICO OBJETIVO;
            :PROPUESTA DE VALOR;
            :RECURSOS CLAVE;
            :ACTIVIDADES CLAVE;
            :RELACIONES CON PÚBLICO OBJETIVO;
            :CANALES;
            split
                :ESTRUCTURA DE COSTOS;
            split again
                :FLUJOS DE INGRESO;
            end split
            :ALIANZAS CLAVE;
        end split
    }
end split

:DOCUMENTACIÓN;
:ACUERDOS;

stop

footer <size:8>Semantyk © 2026</size>

@enduml
