' ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
' # `mereology.puml`
' @organization: Semantyk
' @project: Ecosystem
'
' @file: This file defines the `mereology.puml` diagram.
'
' @created: 2026-08-29 11:27
' @modified: 2026-08-30 03:52
'
' @since: 0.1.0-alpha.10
' @version: 0.1.0-alpha.10
'
' @author: Semantyk Team
' @maintainer: Daniel Bakas <daniel@semantyk.com>
'
' @copyright: Semantyk © 2026
' ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

@startuml "CONTENCIÓN"

'* Imports
!include ../../../../src/packages/ux/styles/mereology.styles.puml

'* Main
mainframe <<mereología>>\n**CONTENCIÓN**

$mereology(CONTENEDOR, 100, 50, CONTENIDO, 52, 35, 59, 104)

footer <size:8>Semantyk © 2026</size>

@enduml
