' ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
' # `taxonomy.puml`
' @organization: Semantyk
' @project: Ecosystem
'
' @file: This file defines the `taxonomy.puml` diagram.
'
' @created: 2026-08-29 11:27
' @modified: 2026-08-30 03:52
'
' @since: 0.1.0-alpha.9
' @version: 0.1.0-alpha.9
'
' @author: Semantyk Team
' @maintainer: Daniel Bakas <daniel@semantyk.com>
'
' @copyright: Semantyk © 2026
' ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

@startmindmap "ARQUITECTURA DE 3 CAPAS"

'* Imports
!include ../../../../../../src/packages/ux/styles/main.styles.puml

mainframe <<taxonomía>>\n**PLATAFORMA**\n(3 CAPAS)

*
 * CLIENTE
 * SERVIDOR
 * DATOS

footer <size:8>Semantyk © 2026</size>

@endmindmap
