' ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
' # `flow.puml`
' @organization: Semantyk
' @project: Ecosystem
'
' @file: This file defines the `flow.puml` diagram.
'
' @created: 2026-08-29 11:27
' @modified: 2026-08-30 03:52
'
' @since: 0.1.0-alpha.18
' @version: 0.1.0-alpha.18
'
' @author: Semantyk Team
' @maintainer: Daniel Bakas <daniel@semantyk.com>
'
' @copyright: Semantyk © 2026
' ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

@startuml "FLUJO DE STATUS"

'* Imports
!include ../../../../../src/packages/ux/styles/main.styles.puml

mainframe <<flujo>>\n**STATUS**

start

partition "PENDIENTES" {
  :S0 · IDEADO;
  :S1 · PROPUESTO;
  :S2 · APROBADO;
  :S3 · ASIGNADO;
}

partition "ACTIVAS" {
  :S4 · INICIADO;
  :S5 · EN CURSO;
  :S6 · AVANZADO;
}

partition "FINALIZADAS" {
  :S7 · REALIZADO;
  :S8 · TERMINADO;
}

stop

footer <size:8>Semantyk © 2026</size>

@enduml
