' ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
' # `taxonomy.puml`
' @organization: Semantyk
' @project: Ecosystem
'
' @file: This file defines the `taxonomy.puml` diagram.
'
' @created: 2026-08-29 11:27
' @modified: 2026-08-29 20:04
'
' @since: 0.1.0-alpha.0
' @version: 0.1.0-alpha.0
'
' @author: Semantyk Team
' @maintainer: Daniel Bakas <daniel@semantyk.com>
'
' @copyright: Semantyk © 2026
' ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

@startmindmap "COMPOSICIÓN DE PROYECTOS"

* ESTRATEGIA
 * PRODUCCIÓN
  *_ INFORMACIÓN
 * SISTEMATIZACIÓN
  *_ DOCUMENTOS
  *_ ARCHIVOS
  *_ METADATOS
  *_ DATOS
  *_ CONJUNTOS
  *_ SISTEMAS
 * INTEROPERABILIDAD
  * INTERNA
   *_ CONANP
   *_ DGIRA
   *_ DGZFMTAC
   *_ DGPEEA
  * EXTERNA
   *_ INEGI
   *_ CEPAL
 * DIFUSIÓN
 * PLATAFORMA
  * FUENTES
   * BASES DE DATOS
    *_ BADESNIARN
  * INFRAESTRUCTURAS
   * SERVICIOS
    *_ MICROSERVICIOS
    *_ CAPA SEMÁNTICA
   * NODOS
    *_ NODO DE DATOS
    *_ NODO DE SERVICIOS
    *_ NODO DE PRODUCTOS
  * PRODUCTOS
   *_ SITIO WEB
    * LÓGICA
    * PRESENTACIÓN
mainframe <<composición>>\n**PROYECTOS**

footer <size:8>Semantyk © 2026</size>

@endmindmap

