#––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
# `compose.yaml`
# @organization: Semantyk
# @project: Ecosystem
#
# @file: This file defines the Docker Compose services for the sandbox apps module.
#
# @created: 2026-08-30 13:38
# @modified: 2026-09-02 11:19
#
# @since: 0.1.0-alpha.37
# @version: 0.1.0-alpha.43
#
# @author: Semantyk Team
# @maintainer: Daniel Bakas <daniel@semantyk.com>
# @copyright: Semantyk © 2026
#––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

include:
  - path: poc/knowledge/compose.yaml

networks:
  sandbox:
    name: sandbox
    driver: bridge

services: {}
