#––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
# `log4j2.properties`
# @organization: Semantyk
# @project: Ecosystem
#
# @file: This file configures logging for the knowledge app.
#
# @created: 2026-09-02 13:38
# @modified: 2026-09-02 13:38
#
# @since: 0.1.0-alpha.42
# @version: 0.1.0-alpha.46
#
# @author: Semantyk Team
# @maintainer: Daniel Bakas <daniel@semantyk.com>
#
# @copyright: Semantyk © 2026
#––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

status = error
name = PropertiesConfig

appender.console.type = Console
appender.console.name = OUT
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{HH:mm:ss} %-5p %-15c{1} :: %m%n

appender.file.type = RollingFile
appender.file.name = FILE
appender.file.fileName = /fuseki/logs/knowledge.log
appender.file.filePattern = /fuseki/logs/knowledge-%d{yyyy-MM-dd}.log.gz
appender.file.layout.type = PatternLayout
appender.file.layout.pattern = [%d{yyyy-MM-dd HH:mm:ss}] %-5p %-15c{1} :: %m%n
appender.file.policies.type = Policies
appender.file.policies.time.type = TimeBasedTriggeringPolicy
appender.file.policies.time.interval = 1

appender.plain.type = RollingFile
appender.plain.name = REQUEST
appender.plain.fileName = /fuseki/logs/requests.log
appender.plain.filePattern = /fuseki/logs/requests-%d{yyyy-MM-dd}.log.gz
appender.plain.layout.type = PatternLayout
appender.plain.layout.pattern = %m%n
appender.plain.policies.type = Policies
appender.plain.policies.time.type = TimeBasedTriggeringPolicy
appender.plain.policies.time.interval = 1

rootLogger.level = INFO
rootLogger.appenderRef.stdout.ref = OUT
rootLogger.appenderRef.file.ref = FILE

logger.jena.name = org.apache.jena
logger.jena.level = INFO

logger.fuseki.name = org.apache.jena.fuseki
logger.fuseki.level = INFO

logger.jetty.name = org.eclipse.jetty
logger.jetty.level = WARN

logger.shiro.name = org.apache.shiro
logger.shiro.level = WARN

logger.shiro-realm.name = org.apache.shiro.realm.text.IniRealm
logger.shiro-realm.level = ERROR

logger.fuseki-request.name = org.apache.jena.fuseki.Request
logger.fuseki-request.additivity = false
logger.fuseki-request.level = INFO
logger.fuseki-request.appenderRef.plain.ref = REQUEST
