#––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
# `shiro.ini`
# @organization: Semantyk
# @project: Ecosystem
#
# @file: This file configures authentication and authorization for the knowledge app.
#
# @created: 2026-09-02 11:29
# @modified: 2026-09-02 12:36
#
# @since: 0.1.0-alpha.42
# @version: 0.1.0-alpha.43
#
# @author: Semantyk Team
# @maintainer: Daniel Bakas <daniel@semantyk.com>
#
# @copyright: Semantyk © 2026
#––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

[main]
ssl.enabled = false

plainMatcher=org.apache.shiro.authc.credential.SimpleCredentialsMatcher
iniRealm.credentialsMatcher = $plainMatcher

[users]
${ADMIN_USER}=${ADMIN_PASSWORD}

[roles]

[urls]
/$/status = anon
/$/ping   = anon
/$/** = authcBasic,user[${ADMIN_USER}]
/*/update/** = authcBasic,user[${ADMIN_USER}]
/*/data/** = authcBasic,user[${ADMIN_USER}]
/**=anon
